[phases.setup]
nixPkgs = ["python311", "chromium", "nss", "nspr", "atk", "at-spi2-atk", "cups", "dbus", "expat", "libdrm", "libxcb", "libxkbcommon", "cairo", "pango", "glib", "alsa-lib", "mesa", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m playwright install chromium",
  "python -m playwright install-deps chromium"
]

[start]
cmd = "python main.py"
